import 'dart:async';

import 'package:chess/models/game_session.dart';
import 'package:chess/models/game_state.dart';
import 'package:chess/screens/game_screen.dart';
import 'package:chess/services/api/game_api_service.dart';
import 'package:chess/services/game_socket_service.dart';
import 'package:chess/services/player_name_service.dart';
import 'package:chess/widgets/confirm_modal.dart';
import 'package:chess/widgets/error_overlay.dart';
import 'package:chess/widgets/loading_dots.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

/// Determines which type of game the waiting screen should create/join.
///
/// The important point is that the previous QuickGameScreen no longer
/// assumes that every game comes from /games/quick.
enum GameMode { public, privateCreate, privateJoin }

enum GameWaitingState { searching, opponentFound, error }

class GameWaitingScreen extends StatefulWidget {
  final GameMode mode;

  /// Only used for privateJoin.
  ///
  /// For privateCreate, the code is generated by the backend and therefore
  /// is not known when this screen is opened.
  final String? code;

  const GameWaitingScreen({super.key, required this.mode, this.code});

  @override
  State<GameWaitingScreen> createState() => _GameWaitingScreenState();
}

class _GameWaitingScreenState extends State<GameWaitingScreen> {
  GameWaitingState _state = GameWaitingState.searching;

  Timer? _transitionTimer;

  GameState? _game;
  String _errorMessage = '';

  GameSession? _session;

  /// The private game code shown by the create flow.
  ///
  /// For privateCreate this comes from the API response.
  /// For privateJoin it is simply the code supplied to this screen.
  String? _privateCode;

  bool _showCancelModal = false;
  bool _allowNavigation = false;

  final GameSocketService _socketService = GameSocketService();

  StreamSubscription<GameSocketMessage>? _socketSubscription;
  StreamSubscription<Object>? _socketErrorSubscription;

  @override
  void initState() {
    super.initState();

    _listenToSocket();

    // The waiting screen is now responsible for starting the game.
    // It chooses the correct API according to widget.mode.
    _startGame();
  }

  void _listenToSocket() {
    _socketSubscription = _socketService.messages.listen(_handleSocketMessage);

    _socketErrorSubscription = _socketService.errors.listen(_handleSocketError);
  }

  void _handleSocketMessage(GameSocketMessage message) {
    if (!mounted) return;

    if (message is GameStartedMessage) {
      setState(() {
        _game = message.game;
        _state = GameWaitingState.opponentFound;
      });

      // We keep the existing small transition delay so the user can
      // actually see the "OPPONENT FOUND" state before entering the game.
      _transitionTimer = Timer(const Duration(milliseconds: 100), () {
        if (!mounted || _game == null || _session == null) return;

        Navigator.of(context).pushReplacement(
          MaterialPageRoute(
            builder: (_) => GameScreen(
              game: _game!,
              session: _session!,
              socket: _socketService,
            ),
          ),
        );
      });
    }

    // if (message is InvalidMessage) {
    //   _setError('The server received an invalid message.');
    // }

    if (message is UnknownMessage) {
      _setError('The server sent an unknown message.');
    }
  }

  void _handleSocketError(Object error) {
    if (!mounted) return;

    _setError('Couldn’t connect to the game server.');
  }

  /// Starts the correct game flow.
  ///
  /// The important architectural change is that the Home/private-selection
  /// UI does NOT call the backend.
  ///
  /// It only opens this screen with a GameMode (and a code for joining).
  /// This method then performs the actual API request.
  Future<void> _startGame() async {
    if (!mounted) return;

    setState(() {
      _state = GameWaitingState.searching;
      _errorMessage = '';
      _game = null;
      _session = null;
      _privateCode = null;
    });

    try {
      final nickname = await PlayerService.getPlayerName();

      if (!mounted) return;

      switch (widget.mode) {
        case GameMode.public:
          // POST /games/quick
          final response = await GameApiService.quickGame(nickname);

          _session = response.session;
          break;

        case GameMode.privateCreate:
          // POST /games/private
          //
          // The backend generates the private game code.
          final response = await GameApiService.createPrivateGame(nickname);

          if (!mounted) return;

          setState(() {
            _session = response.session;
            _privateCode = response.code;
          });

          break;

        case GameMode.privateJoin:
          // POST /games/private/join
          final code = widget.code?.trim();

          if (code == null || code.isEmpty) {
            _setError('A game code is required.');
            return;
          }

          final response = await GameApiService.joinPrivateGame(nickname, code);

          _session = response.session;
          break;
      }

      if (!mounted || _session == null) return;

      // All game modes use the same session-based WebSocket connection.
      _socketService.connect(session: _session!);
    } catch (error) {
      if (!mounted) return;

      if (widget.mode == GameMode.privateJoin) {
        // ApiClient now includes the backend response body.
        //
        // The backend returns 404 when the code is invalid,
        // the private game does not exist, or the room is full.
        final message = error.toString();

        if (message.contains('404') ||
            message.contains('private game not found or full')) {
          _setError(
            'The game code is invalid or the game is no longer available.',
          );
          return;
        }
      }

      _setError('Couldn’t connect to the game server.');
    }
  }

  void _setError(String message) {
    if (!mounted) return;

    setState(() {
      _state = GameWaitingState.error;
      _errorMessage = message;
    });
  }

  Future<void> _handleRetry() async {
    _socketService.close();

    await _startGame();
  }

  void _handleBack() {
    if (_state == GameWaitingState.error || _allowNavigation) {
      Navigator.of(context).pop();
      return;
    }

    setState(() {
      _showCancelModal = true;
    });
  }

  void _keepWaiting() {
    setState(() {
      _showCancelModal = false;
    });
  }

  Future<void> _confirmCancel() async {
    if (_session == null) {
      _socketService.close();
      _goBack();
      return;
    }

    try {
      await GameApiService.quitGame(sessionId: _session!.sessionId);
    } catch (e) {
      // Cancelling is best-effort.
      //
      // Even if the DELETE fails, we still close the socket and leave
      // the waiting screen.
    }

    if (!mounted) return;

    _socketService.close();

    setState(() {
      _allowNavigation = true;
      _showCancelModal = false;
    });

    if (!mounted) return;

    _socketService.dispose();
    Navigator.of(context).pop();
  }

  Future<void> _copyPrivateCode() async {
    if (_privateCode == null) return;

    await Clipboard.setData(ClipboardData(text: _privateCode!));

    if (!mounted) return;

    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Game code copied'),
        duration: Duration(seconds: 1),
      ),
    );
  }

  @override
  void dispose() {
    _transitionTimer?.cancel();
    _socketSubscription?.cancel();
    _socketErrorSubscription?.cancel();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).colorScheme;

    return PopScope(
      canPop: _state == GameWaitingState.error || _allowNavigation,
      onPopInvokedWithResult: (didPop, result) {
        if (didPop) return;

        _handleBack();
      },
      child: Scaffold(
        body: SafeArea(
          child: Stack(
            children: [
              _buildContent(),

              if (_state == GameWaitingState.error)
                ErrorOverlay(
                  title: widget.mode == GameMode.privateJoin
                      ? 'JOIN GAME'
                      : 'CONNECTION ERROR',
                  message: _errorMessage.isEmpty
                      ? 'Couldn’t connect to the game server.'
                      : _errorMessage,
                  primaryButtonText: 'TRY AGAIN',
                  secondaryButtonText: 'GO BACK',
                  onPrimaryPressed: _handleRetry,
                  onSecondaryPressed: _goBack,
                ),

              if (_showCancelModal)
                Positioned.fill(
                  child: Container(
                    color: colors.scrim.withValues(alpha: 0.5),
                    alignment: Alignment.center,
                    child: ConfirmModal(
                      title: _isPrivateMode
                          ? 'LEAVE PRIVATE GAME?'
                          : 'CANCEL MATCHMAKING?',
                      message: 'Are you sure you want to quit?',
                      confirmText: 'LEAVE GAME',
                      cancelText: 'KEEP WAITING',
                      onConfirm: _confirmCancel,
                      onCancel: _keepWaiting,
                    ),
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildContent() {
    switch (_state) {
      case GameWaitingState.searching:
        return _buildSearching();

      case GameWaitingState.opponentFound:
        return _buildOpponentFound();

      case GameWaitingState.error:
        return _buildSearching();
    }
  }

  Widget _buildSearching() {
    final theme = Theme.of(context);
    final colors = theme.colorScheme;

    final isPrivateCreate = widget.mode == GameMode.privateCreate;
    final isPrivateJoin = widget.mode == GameMode.privateJoin;

    String title;
    String subtitle;

    if (isPrivateCreate) {
      title = 'PRIVATE GAME';
      subtitle = 'Share the code with your opponent';
    } else if (isPrivateJoin) {
      title = 'JOINING GAME';
      subtitle = 'Waiting for the game to start...';
    } else {
      title = 'FINDING OPPONENT';
      subtitle = 'Waiting for a player to join...';
    }

    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            '♟',
            style: TextStyle(fontSize: 64, color: colors.primary, height: 1),
          ),

          const SizedBox(height: 24),

          Text(
            title,
            style: theme.textTheme.headlineSmall?.copyWith(
              fontWeight: FontWeight.bold,
              letterSpacing: 2,
            ),
          ),

          const SizedBox(height: 12),

          Text(
            subtitle,
            style: theme.textTheme.bodyMedium?.copyWith(
              color: colors.onSurface.withValues(alpha: 0.65),
            ),
          ),

          // Only private game creation needs to show the generated code.
          if (isPrivateCreate && _privateCode != null) ...[
            const SizedBox(height: 28),

            _buildPrivateCode(),

            const SizedBox(height: 24),
          ] else
            const SizedBox(height: 24),

          const LoadingDots(),
        ],
      ),
    );
  }

  Widget _buildPrivateCode() {
    final theme = Theme.of(context);
    final colors = theme.colorScheme;

    return Column(
      children: [
        Text(
          'GAME CODE',
          style: theme.textTheme.labelMedium?.copyWith(
            letterSpacing: 1.5,
            fontWeight: FontWeight.w600,
            color: colors.onSurface.withValues(alpha: 0.6),
          ),
        ),

        const SizedBox(height: 8),

        InkWell(
          onTap: _copyPrivateCode,
          borderRadius: BorderRadius.circular(12),
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 12),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: colors.outline.withValues(alpha: 0.5)),
              color: colors.surface,
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  _privateCode!,
                  style: theme.textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.bold,
                    letterSpacing: 3,
                  ),
                ),

                const SizedBox(width: 12),

                Icon(Icons.copy_rounded, size: 20, color: colors.primary),
              ],
            ),
          ),
        ),

        const SizedBox(height: 6),

        Text(
          'Tap to copy',
          style: theme.textTheme.bodySmall?.copyWith(
            color: colors.onSurface.withValues(alpha: 0.5),
          ),
        ),
      ],
    );
  }

  Widget _buildOpponentFound() {
    final theme = Theme.of(context);

    final white = _game?.white;
    final black = _game?.black;

    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            'OPPONENT FOUND',
            style: theme.textTheme.headlineSmall?.copyWith(
              fontWeight: FontWeight.bold,
              letterSpacing: 2,
            ),
          ),

          const SizedBox(height: 40),

          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              _buildPlayer(nickname: white?.nickname ?? 'White', isWhite: true),

              const SizedBox(width: 28),

              Text(
                'VS',
                style: theme.textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),

              const SizedBox(width: 28),

              _buildPlayer(
                nickname: black?.nickname ?? 'Black',
                isWhite: false,
              ),
            ],
          ),

          const SizedBox(height: 40),

          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Starting', style: theme.textTheme.bodyLarge),

              const SizedBox(width: 12),

              const LoadingDots(),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildPlayer({required String nickname, required bool isWhite}) {
    final theme = Theme.of(context);
    final colors = theme.colorScheme;

    return Column(
      children: [
        Container(
          width: 64,
          height: 64,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            color: colors.surface,
            border: Border.all(width: 1),
          ),
          alignment: Alignment.center,
          child: Text(
            '♔',
            style: TextStyle(fontSize: 36, color: colors.primary, height: 1),
          ),
        ),

        const SizedBox(height: 10),

        SizedBox(
          width: 100,
          child: Text(
            nickname,
            textAlign: TextAlign.center,
            overflow: TextOverflow.ellipsis,
            style: theme.textTheme.bodyMedium?.copyWith(
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
      ],
    );
  }

  bool get _isPrivateMode {
    return widget.mode == GameMode.privateCreate ||
        widget.mode == GameMode.privateJoin;
  }

  void _goBack() {
    setState(() {
      _allowNavigation = true;
    });

    Navigator.of(context).pop();
  }
}
